//
//  NativeLatexRenderer.mm
//  LatexNative
//
//  TurboModule shim for the LaTeX renderer. This file exists in Objective-C++ rather
//  than Swift because the TurboModule contract is C++: -getTurboModule: returns a
//  std::shared_ptr, which Swift cannot express. All real work lives in
//  LatexRenderer.swift; this is only the plumbing that connects it to JavaScript.
//

#import <React/RCTBridgeModule.h>
#import <NativeLatexRendererSpec/NativeLatexRendererSpec.h>

// Xcode does not enable Clang modules for Objective-C++, so the `@import`s inside the
// generated Swift header are skipped and its superclasses must be imported by hand.
// AppDelegate.swift's ReactNativeDelegate is declared there too, hence this include.
#import <React-RCTAppDelegate/RCTDefaultReactNativeFactoryDelegate.h>

// Auto-generated by Xcode from the target's @objc Swift declarations.
#import "LatexNative-Swift.h"

// NativeLatexRendererSpec is the protocol codegen derived from specs/NativeLatexRenderer.ts.
// Conforming to it means the compiler enforces that our selector matches the JS signature.
@interface NativeLatexRenderer : NSObject <NativeLatexRendererSpec>
@end

@implementation NativeLatexRenderer

// Registers the module with React Native under its class name, which is the string
// TurboModuleRegistry.get('NativeLatexRenderer') looks up from JS.
RCT_EXPORT_MODULE()

// Nothing here touches UIKit at init time, so React Native is free to set us up
// on a background thread.
+ (BOOL)requiresMainQueueSetup
{
  return NO;
}

- (void)renderLatex:(NSString *)expression
           textSize:(double)textSize
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject
{
  [LatexRenderer renderExpression:expression
                        textSize:textSize
                      completion:^(NSDictionary<NSString *, id> *_Nullable result,
                                   NSString *_Nullable errorCode,
                                   NSString *_Nullable errorMessage) {
    // Resolving/rejecting is thread-safe; React Native marshals back to JS itself.
    if (result != nil) {
      resolve(result);
    } else {
      reject(errorCode, errorMessage, nil);
    }
  }];
}

// Hands React Native the codegen'd C++ binding object for this module. This is the
// one piece that forces the file to be Objective-C++.
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeLatexRendererSpecJSI>(params);
}

@end
